apiVersion: v1
kind: ConfigMap
metadata:
  name: service-config
data:
  services.yaml: |
    services:
    - name: restapi
      type: rest
      port: 8080
      namespace: api
      health_path: /health
    - name: postgresql
      type: postgresql
      namespace: database
      port: 5432
      db_name: db