apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service-monitor
spec:
  ingressClassName: nginx
  rules:
  - host: service-monitor.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-monitor
            port:
              number: {{ .Values.serviceMonitorPort }}